# Generated by Django 6.0.5 on 2026-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nis', models.CharField(max_length=50, unique=True, verbose_name='NIS')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('ustadz_pembina', models.CharField(default='Belum diisi', max_length=150)),
                ('nama_orang_tua', models.CharField(max_length=150)),
                ('nomor_wa_orang_tua', models.CharField(max_length=20, verbose_name='Nomor WhatsApp Orang Tua')),
                ('alamat', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Santri',
                'ordering': ['nama'],
            },
        ),
    ]
