# Generated by Django 6.0.5 on 2026-06-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_awal', models.DateField()),
                ('periode_akhir', models.DateField()),
                ('total_setoran', models.PositiveIntegerField(default=0)),
                ('rata_rata_setoran_harian', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hafalan_terakhir', models.CharField(blank=True, max_length=200)),
                ('kategori_juz_terakhir', models.CharField(blank=True, max_length=50)),
                ('catatan_perkembangan', models.TextField(blank=True)),
                ('status_pengiriman', models.CharField(choices=[('belum_dikirim', 'Belum Dikirim'), ('simulated', 'Simulasi'), ('sent', 'Terkirim'), ('failed', 'Gagal')], default='belum_dikirim', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_hafalan', to='santri.santri')),
            ],
            options={
                'verbose_name': 'Laporan Hafalan',
                'verbose_name_plural': 'Laporan Hafalan',
                'ordering': ['-periode_akhir', 'santri__nama'],
            },
        ),
    ]
