# Generated by Django 6.0.5 on 2026-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halaqah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120, unique=True)),
                ('ustadz_pembimbing', models.CharField(max_length=150)),
                ('target_hafalan', models.CharField(blank=True, max_length=120)),
                ('keterangan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Halaqah',
                'verbose_name_plural': 'Halaqah',
                'ordering': ['nama'],
            },
        ),
    ]
