# Generated by Django 6.0.5 on 2026-06-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetoranHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_setoran', models.CharField(choices=[('ziyadah', 'Ziyadah'), ('murajaah', 'Murajaah')], max_length=20)),
                ('kategori_juz', models.CharField(choices=[('juz_1_5', '1-5 Juz'), ('juz_1_10', '1-10 Juz'), ('juz_1_15', '1-15 Juz'), ('juz_1_20', '1-20 Juz'), ('juz_1_25', '1-25 Juz'), ('juz_1_30', '1-30 Juz')], default='juz_1_5', max_length=20)),
                ('surah', models.CharField(max_length=100)),
                ('halaman_awal', models.PositiveIntegerField()),
                ('halaman_akhir', models.PositiveIntegerField()),
                ('kualitas', models.CharField(choices=[('sangat_baik', 'Sangat Baik'), ('baik', 'Baik'), ('cukup', 'Cukup'), ('perlu_bimbingan', 'Perlu Bimbingan')], default='baik', max_length=30)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setoran_hafalan', to='santri.santri')),
            ],
            options={
                'verbose_name': 'Setoran Hafalan',
                'verbose_name_plural': 'Setoran Hafalan',
                'ordering': ['-tanggal', 'santri__nama'],
            },
        ),
    ]
