# Generated by Django 6.0.5 on 2026-06-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tujuan', models.CharField(max_length=20)),
                ('pesan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('simulated', 'Simulasi'), ('sent', 'Terkirim'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('laporan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='laporan.laporanhafalan')),
            ],
            options={
                'verbose_name': 'Log WhatsApp',
                'verbose_name_plural': 'Log WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
