# Generated by Django 6.0.5 on 2026-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(default='SMHTAHFIDZ-ZBT', max_length=200)),
                ('token', models.CharField(max_length=255)),
                ('nomor_gateway', models.CharField(max_length=20)),
                ('country_code', models.CharField(default='62', max_length=5)),
                ('simulation_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
